spring.datasource.url=jdbc:sqlserver://172.25.48.1:1433;databaseName=MisEspaciosDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Admin1_admin1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
logging.level.org.springframework.security=DEBUG

